# Into to NumPy

In [1]:
import numpy as np


# NumPy arrays

In [2]:
# Creating an array of predefined size filled with zero

zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# Creating an array filled with ones

ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
# Another way

array = np.full(10,0.0)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# Another way

array = np.repeat(0.0,10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#using np repeat

array = np.repeat([0.0,1.0],5)
array

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [7]:
# Another np repeat ex

array = np.repeat([0.0,1.0],[2,3])
array

array([0., 0., 1., 1., 1.])

In [8]:
el = array[0]
print(el)

0.0


In [9]:
# accessing multiple elements at the same time 

print(array[[4,2,0]])

[1. 1. 0.]


In [10]:
# Converting a list to a numpy array

elements = [1,2,3,4]
array = np.array(elements)
array

array([1, 2, 3, 4])

In [11]:
#using the arange method

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Using linspace

thresholds = np.linspace(0,1,11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
# Specifyign the dtype when creating an array

zeros = np.zeros(10,dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [14]:
# Checking what happens if we assign a number outside the type range

zeros[0] = 300
print(zeros[0])

44


In [15]:
# Iterating over all the elements of an array 

for i in np.arange(5):
  print(i)

0
1
2
3
4


# 2d NumPy Arrays

In [16]:
# creating a 2d array with zeros

zeros = np.zeros((5,2),dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [17]:
#Getting the shape of an array

zeros.shape

(5, 2)

In [18]:
#convert a python list of lists to a numpy array

numbers = [[1,2,3],[4,5,6],[7,8,9]]
numbers = np.array(numbers)
numbers

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# accessing an element in the 2d array

numbers[0,1]

2

In [20]:
# Assign a value to the array

numbers[0,1] = 10

numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
#getting a row

numbers[0]

array([ 1, 10,  3])

In [22]:
# To access a column 

numbers[:,1]

array([10,  5,  8])

In [23]:
#overwritting an entire row

numbers[1] = [1,1,1]
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [24]:
# Replace an entire col

numbers[:,2] = [9,9,9]
numbers

array([[ 1, 10,  9],
       [ 1,  1,  9],
       [ 7,  8,  9]])

# Randomly generated arrays 

In [25]:
# Creating a 5x2 array of random numbers uniformly distributed between 0 and 1

arr = np.random.rand(5,2)
arr

array([[0.74079797, 0.39816557],
       [0.35742446, 0.43646263],
       [0.39395409, 0.11121212],
       [0.05174053, 0.95675582],
       [0.5190857 , 0.83337613]])

In [26]:
# Using a seed to produce the same results everytime the code is ran

np.random.seed(0)
arr = np.random.rand(5,2)
arr

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152]])

In [27]:
# For standard normal distribution 

arr = np.random.randn(5,2)

In [28]:
# Generating a uniformly distributed random integers between 0 and 100 

randint = np.random.randint(low = 0, high=100, size=(5,2))
randint

array([[ 9, 57],
       [32, 31],
       [74, 23],
       [35, 75],
       [55, 28]])

In [29]:
# Creating an array with arange and shuffling it

idx = np.arange(5)

print("before shuffle:",idx)

np.random.shuffle(idx)
print("after shuffle:",idx)

before shuffle: [0 1 2 3 4]
after shuffle: [1 4 3 0 2]


# C.2 Numpy operations

In [30]:
#creating a numpy array

rng = np.arange(5)

In [31]:
# Multiply every element in the array by 2

rng * 2

array([0, 2, 4, 6, 8])

In [32]:
# applying multiple operations at once in one expression

(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [33]:
# creating 2 arrays

noise = 0.01 * np.random.rand(5)
numbers = np.arange(5)
print(noise)
print(numbers)

[0.00617635 0.00612096 0.00616934 0.00943748 0.0068182 ]
[0 1 2 3 4]


In [34]:
# Adding the 2 numpy arrays
results = numbers + noise
results

array([0.00617635, 1.00612096, 2.00616934, 3.00943748, 4.0068182 ])

In [35]:
# Rounding the numbers to any precision

results.round(4)

array([0.0062, 1.0061, 2.0062, 3.0094, 4.0068])

In [36]:
# Generating a random array

pred = np.random.rand(3).round(2)
pred

array([0.36, 0.44, 0.7 ])

In [37]:
#squaring each element in the array

square = pred **2
square

array([0.1296, 0.1936, 0.49  ])

In [38]:
# Creating another array

pred = np.random.rand(3).round(2)
pred

array([0.06, 0.67, 0.67])

In [39]:
# create a boolean arrays to see which elements are greater than 0.5

results = pred >= 0.5
results

array([False,  True,  True])

In [40]:
# Creating two random arrays 

pred1 = np.random.rand(3).round(2)
pred2 = np.random.rand(3).round(2)

print(pred1)
print(pred2)

[0.21 0.13 0.32]
[0.36 0.57 0.44]


In [41]:
# comparing each array using >=

pred1 >= pred2

array([False, False, False])

In [42]:
# Creating boolean arrays to perform logical operations

pred1 = np.random.rand(5) >= 0.3
pred2 = np.random.rand(5) >= 0.4

print(pred1)
print(pred2)

[ True False False False  True]
[False  True False False False]


In [43]:
res_and = pred1 & pred2
res_and

array([False, False, False, False, False])

In [44]:
res_or = pred1 | pred2
res_or

array([ True,  True, False, False,  True])

# C.2.2 Summarizing operations

In [45]:
# Creating a random array and obtaining the sum

pred = np.random.rand(3).round(2)
pred_sum = pred.sum()

print(pred)
print(pred_sum)

[0.66 0.14 0.2 ]
1.0


In [46]:
# other summarizing operations include min mean max std

print("min = {:.2f}".format(pred.min()))
print("mean = {:.2f}".format(pred.mean()))
print("max = {:.2f}".format(pred.max()))
print("std = {:.2f}".format(pred.std()))

min = 0.14
mean = 0.33
max = 0.66
std = 0.23


In [47]:
# Creating a random 2d array

matrix = np.random.rand(4,3).round(2)
matrix

array([[0.37, 0.82, 0.1 ],
       [0.84, 0.1 , 0.98],
       [0.47, 0.98, 0.6 ],
       [0.74, 0.04, 0.28]])

In [48]:
# obtaining overall max

matrix.max()

0.98

In [49]:
#obtain the max of each row

matrix.max(axis=1)

array([0.82, 0.98, 0.98, 0.74])

In [50]:
#obtaining the max of each col

matrix.max(axis=0)

array([0.84, 0.98, 0.98])

# C.2.3 Sorting

In [51]:
# creating a random 1d array

pred = np.random.rand(4).round(2)
pred

array([0.12, 0.3 , 0.12, 0.32])

In [52]:
# To create a sorted copy of the array

np.sort(pred)

array([0.12, 0.12, 0.3 , 0.32])

In [53]:
# To sort in place
pred.sort()
pred

array([0.12, 0.12, 0.3 , 0.32])

In [54]:
# Using argsort to return the indices of the array

idx = pred.argsort()
idx

array([0, 1, 2, 3])

# C.2.4 Reshaping and combining

In [55]:
# Creating an array

rng = np.arange(12)
rng.shape

(12,)

In [56]:
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [57]:
# Using the reshape method to change the shape of the 1d array to a 2d array

rng.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
# Creating 2 arrays

vec = np.arange(3)
mat = np.arange(6).reshape(3,2)
mat

array([[0, 1],
       [2, 3],
       [4, 5]])

In [59]:
# combining 2 arrays using np.concatenate

np.concatenate([vec,vec])

array([0, 1, 2, 0, 1, 2])

In [60]:
# Achieving the same results using the np.stack 

np.hstack([vec,vec])

array([0, 1, 2, 0, 1, 2])

In [61]:
# Also apply hstack to 2d arrays

np.hstack([mat,mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [62]:
# with 2d arrays np.concatenate works different
np.concatenate([mat,mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [63]:
# using np.column_stack to add a vector to a 2d array as a col

np.column_stack([vec,mat])

array([[0, 0, 1],
       [1, 2, 3],
       [2, 4, 5]])

In [64]:
# np.vstack stacks arrays vertically

np.vstack([vec,vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [65]:
# stack 2 matrices vertically

np.vstack([mat,mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

# C.2.5 Slicing and filtering

In [67]:
#create a 5x3 matrix

mat = np.arange(15).reshape(5,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
# Getting the first 3 rows

mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
#Getting rows 1 and 2 

mat[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [70]:
# getting all rows but only the first two columns

mat[:,:2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [71]:
#selecting any matrix part we want

mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [72]:
#obtaining specfic rows 

mat[[3,0,1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [74]:
#choosing all rows where the first element of a row is an odd number

#here's the boolean mask

mat[:,0] % 2 == 1

array([False,  True, False,  True, False])

In [75]:
# Using the above boolean mask to obtain only the rows where the first element is odd

mat[mat[:,0]%2==1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])